### ISSUE TITLE
not working after integrating with ui-app-hub and dashboard-microapp

### ISSUE THREAD

**Issue by learner1024** [PredixDev/px-vis-spark#1]
Expected Behavior
The sparkline should be drawn starting from beginning of rectangle

Actual behaviour
one the demo page it does quite well, as expected, however when we integrate it in dashboard-microapp along with ui-app-hub, it does not work. Please have a look at screenshot.

![image](https://cloud.githubusercontent.com/assets/10090811/19554808/e084a102-96d7-11e6-8670-1405dbbad2b5.png)

Thanks,
Sandeep Khandewale

**Comment by randyaskin** [comment]
You're essentially saying "your code works, except when we combine it with other code, then it breaks" - as you can imagine, it's pretty much impossible for our team to support issues of this nature. Unless you can show us the actual root cause in a working CodePen or something, I'm not sure how to help you.

**Comment by rupeshpadhye** [comment]
Hi @randyaskin 
We have simulated issue ,
[px-vis-spark-rendering-issue.zip](https://github.com/PredixDev/px-vis-spark/files/558259/px-vis-spark-rendering-issue.zip)

Issue setup -
1. put test.html in base directory of the px-vis-spark
2. run node webservice from backend folder

**Requirement** -
We have one Microservice providing time service data as per user chosen time frame.
on UI front, we are doing two way data binding for data consumption

**Observation**s -
1. There is hard coded defaultData in px-vis-spark.html.
2. graph is plotted if data is starting from  1397102460000 timestamp(First value of defaultData) but
   if we receive different time frame then graph is distorted
3. px-vis-line using single binding of variables

**Need Help** -
- Way to send notification to px-vis-line to redraw itself
- Recalculate width/height if we resize cards (Not window)

**Comment by randyaskin** [comment]
Thanks @rupeshpadhye, this helps greatly in diagnosing the problem! Sorry for my earlier comments, this does indeed sound like an issue with our component. I'll take a look at what you provided and get a fix out ASAP.

**Comment by randyaskin** [comment]
@rupeshpadhye I've pushed up a new version that just removes the default data, that seemed to fix the extents issue when I ran it with your express server (thanks again for that). My Travis build is failing due to a unit test issue I need to fix, but can you take a look and let me know if you're still having issues with the latest version?

**Comment by rupeshpadhye** [comment]
Thank you @randyaskin  for taking issue on priority. 
We need  some more fixes to fit this scenario :sweat_smile:

> time frame of the x-axis is not recalculated again

 e.g. User selects time frame as last one year and graph is plotted, Again user changes time span to last six months ,then px-vis-line will be plotted from middle of allotted svg area  instead of starting.

 We can have something `data_changed_event` which will trigger`px-vis-scale` and `px-vis-svg` again
to do recalculation of min/max x and y axis.(redraw event)

update -

Findings -
- px-vis-behaviour-chart.html has this.chartExtents which holds min and max of x and y axis.
- There is  something 'px-vis-current-domain-x-updated' event..But I am not able to leverage it
