### ISSUE TITLE
Allow theming of line using CSS vars

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis-spark#4]

**Comment by randyaskin** [comment]
Technically it needs to be an area, rather than a line, to support the gradient fill underneath, which has always been the intended design. But that too should be style-able using CSS vars.

![screen shot 2017-03-02 at 12 18 48 pm](https://cloud.githubusercontent.com/assets/2130613/23525180/69c5ed22-ff42-11e6-8ebc-928c1605260d.png)

**Comment by randyaskin** [comment]
It can be done with `--px-vis-series-color-0` - we could either add that to the documentation, or wrap it in a new CSS variable specific to this component.

**Comment by nonmetalhail** [comment]
Done with design refresh
